resources:
- name: lock
  type: pool
  source:
    uri: hhttps://github.com/tonyelmore/telmore.git
    branch: master
    username: ((github_username))
    password: ((github_token))
    pool: locks/((lock_pool_name))
    retry_delay: 1m

jobs:
- name: force-unlock
  serial: true
  plan:
  - get: lock
  - put: lock
    params:
      release: lock

- name: lock-director
  serial: true
  plan:
  - aggregate:
    - get: lock
    - put: lock
      params: {acquire: true}

- name: HelloWorld
  public: true
  plan:
    - get: lock
      trigger: true
      passed:
      - "lock-director"
    - task: PrintItOut
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: busybox }
        run:
          path: echo
          args: ["Hello, World!"]

- name: unlock-director
  serial: true
  plan:
  - get: lock
    trigger: true
    passed:
    - "HelloWorld"
  - put: lock
    params:
      release: lock