confirm_tls_setup: 
dev_plan_enable_service_plan_enable_service_instance_azs: pas-az1
network_name: PAS-Deployment
plan1_enable_service_plan_enable_service_instance_azs: pas-az1
service_network_name: PAS-Services
singleton_availability_zone: pas-az1
small_footprint_enable_service_plan_enable_service_instance_azs: pas-az1
