errand-runner/ingestor_instance_count: 1
errand-runner/logs_queue_instance_count: 1
errand-runner/logs_queue_max_retention_percentage: 85
errand-runner/logs_queue_retention_percentage_interval: 1h
errand-runner/logs_retention_window: 14
errand-runner/metrics_queue_instance_count: 1
errand-runner/metrics_retention_window: 14
errand-runner/push_apps_log_level: error
errand-runner/server_instance_count: 1
delete-prior-space_post_deploy_state: default
delete-space_pre_delete_state: default
migrate-route_post_deploy_state: default
push-apps_post_deploy_state: default
smoke-tests_post_deploy_state: default
errand-runner_instance_type: automatic
errand-runner_persistent_disk_size: automatic
mysql_instance_type: automatic
mysql_persistent_disk_size: automatic
postgres_instance_type: automatic
postgres_persistent_disk_size: automatic
redis_instance_type: automatic
redis_persistent_disk_size: automatic
