healthwatch-forwarder_boshhealth_instance_count: 1
healthwatch-forwarder_boshtasks_instance_count: 2
healthwatch-forwarder_canary_instance_count: 2
healthwatch-forwarder_cli_instance_count: 2
healthwatch-forwarder_ingestor_instance_count: 4
healthwatch-forwarder_opsman_instance_count: 2
healthwatch-forwarder_publish_to_eva: true
healthwatch-forwarder_worker_instance_count: 1
delete-space_pre_delete_state: default
push-apps_post_deploy_state: default
smoke-tests_post_deploy_state: default
healthwatch-forwarder_instance_type: automatic
healthwatch-forwarder_instances: automatic
healthwatch-forwarder_max_in_flight: default
healthwatch-forwarder_persistent_disk_size: automatic
mysql_instance_type: automatic
mysql_instances: automatic
mysql_max_in_flight: default
mysql_persistent_disk_size: automatic
redis_instance_type: automatic
redis_instances: automatic
redis_max_in_flight: default
redis_persistent_disk_size: automatic
