credhub_key_encryption_passwords_0/key: ((credhub_key_encryption_password))
credhub_key_encryption_passwords_0/name: key

networking_poe_ssl_certs_0/certificate: ((pas_network_cert.certificate))
networking_poe_ssl_certs_0/name: router-cert
networking_poe_ssl_certs_0/privatekey: ((pas_network_cert.private_key))

credhub_hsm_provider_client_certificate/certificate: ((credhub_hsm_provider_client.certificate))
credhub_hsm_provider_client_certificate/privatekey: ((credhub_hsm_provider_client.private_key))

uaa/service_provider_key_credentials/certificate: ((uaa_service_provider_key_credentials.certificate))
uaa/service_provider_key_credentials/privatekey: ((uaa_service_provider_key_credentials.private_keuy))